speller_config:
  sentences_path: datasets/with_brands/brand-freq-dict.txt.gz
  dict_path: datasets/with_brands/brand-freq-dict.txt.gz
  min_word_freq: 5
  min_word_length: 3
  unigram_weight: 100
  bigram_weight: 50
  trigram_weight: 80
  auto_train_mode: false
nats_config:
  